name: deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: ${{ secrets.DEPLOYKEY }}
    - name: push master
      env:
        API_URL: https://api.alesap.astrobunny.net
      run: |-
        git config --global user.name "blankaex(ghactions)"
        git config --global user.email "5815849+blankaex@users.noreply.github.com"
        sh deploy.sh

'on':
  push:
    branches:
    - '*'
